language: python
python:
    - "3.7"

envs:
  global:
    - DENGO_INSTALL_PATH=$(TRAVIS_BUILD_DIR)/dengo_install
    - CVODE_PATH=$(TRAVIS_BUILD_DIR)/cvode-3.1.0/instdir
    - HDF5_PATH=$(TRAVIS_BUILD_DIR)/hdf5_install
    - SUITESPARSE_PATH=$(TRAVIS_BUILD_DIR)/SuiteSparse
    - HDF5_DIR=$(TRAVIS_BUILD_DIR)/hdf5_install

before_install:
    - sudo apt-get install gfortran
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/suitesparse/OpenBLAS
    - ./install-suitesparse.sh 
    - ./install-cvode3.1.sh &> cvode_install.out
    - ./install-chiantipy.sh &> chiantipy_install.out
    - ./install-hdf5.sh  
    - ./install-yt.sh &> yt_install.out
#    - ./install-grackle.sh
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install h5py
    - pip install sympy
    - pip install -e .
# command to run tests
script:
    - echo $(SUITESPARSE_PATH)
    - echo $(HDF5_PATH)
    - echo $(DENGO_INSTALL_PATH)
    - pytest -v examples/test/


